### ISSUE TITLE
Sign-up buttons are not visible on mobile

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-login-ux#101]
Platform: Android 4.4
Browser: Firefox (Latest)

When creating an account from Webmaker.org (staging) on a mobile device such as Firefox on Android the "Cancel" and "Next" buttons are not displayed properly:
![screenshot_2014-12-19-12-16-08](https://cloud.githubusercontent.com/assets/747641/5528751/ad18b630-89c0-11e4-818b-b70f348533be.png)

This *may* be due to sizing / scaling differences between Webmaker.app and the modal that this screen is rendered within on Webmaker.org

**Comment by jbuck** [comment]
I've fixed the modal so it shows as fullscreen now; just need to fix the title now.
