### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-login-ux#113]
Pressing `enter` after entering a username/email address (rather than tapping button) triggers Persona modal. (wm.org on FF Dev 36)

**Comment by Pomax** [comment]
I can't reproduce this (anymore?). Followed steps:

- run login + makeapi + webmaker.org + Es + mongo
- open localhost:7777
- click "sign in"
- fill in email address
- hit "enter" rather than pressing button

this transitions me to "check your email" (with a token in the nodejs console).

**Comment by jbuck** [comment]
@gvn fixed this in https://github.com/mozilla/webmaker-login-ux/commit/3dca8c13a6a6b8e1596a027cf9bb75275f65d9e7
