### ISSUE TITLE
No emails on Thimble Join

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-login-ux#119]
Platform: OS X 10.9.5
Browser: FF Dev 36.0a2

URL: https://thimble.mofostaging.net/

I joined thimble successfully, but did not receive a welcome email. Did not receive an email on sign in either. Repeated 3 times with different addresses to confirm it wasn't spam or typos.

**Comment by jbuck** [comment]
I'm going to chalk this up to a transient error in sawmill/lumberyard, probably caused by @secretrobotron's invalid email testing :)

Closing for now.

**Comment by secretrobotron** [comment]
# ᕕ( ᐛ)ᕗ
