### ISSUE TITLE
Language menu broke on goggles

### ISSUE THREAD

**Issue by xmatthewx** [mozilla/webmaker-login-ux#121]
Platform: OS X 10.9.5
Browser: FF Dev 36.0a2
URL: https://goggles.mofostaging.net/
Scenario: Switch locale

Menu falls behind content. Does not occur in app on production.

**Comment by Pomax** [comment]
looks like goggles `webmaker-nav-container` has an `overflow: hidden` rule that prevents content from making it out of the parent div, like menu selectors.

**Comment by Pomax** [comment]
https://github.com/mozilla/goggles.webmaker.org/pull/146 should fix this.
