### ISSUE TITLE
Header in "My Makes" section does not reflect logged-in state

### ISSUE THREAD

**Issue by thisandagain** [mozilla/webmaker-login-ux#136]
Browser: Chrome 39.0.2171.95
Platform: Mac OS 10.10.1

Steps to reproduce:
- Sign-in using an existing account from the splash / landing page
- Navigate to "My Makes"
- Header does not reflect logged-in state

![screen shot 2015-01-06 at 3 19 50 pm](https://cloud.githubusercontent.com/assets/747641/5638109/cceea782-95b7-11e4-8033-c9ed2be2553d.png)

**Comment by jbuck** [comment]
This was caused by Newrelic RUM being enabled. Disabling it prevents the issue from occuring. I suspect we'll need to write a patch for `browser-request` before we can use it with RUM enabled.
