### ISSUE TITLE
Move the send me emails checkbox from dialog 1 in the sign up process to later in the process

### ISSUE THREAD

**Issue by ScottDowne** [mozilla/webmaker-login-ux#140]
Right now, the first dialog in the sign up process looks like this:

![step2](https://cloud.githubusercontent.com/assets/197334/5685792/dd6fba0a-980b-11e4-8964-741c80ef420c.png)

We have had chats about moving the "send emails to me" checkbox to later in the process.

How feasible would this be and what ideas to we have about where is we can put it? Putting it in step two comes to mind but I'm not sure if that makes sense.

The advantage to not having it in step 1 is it makes the act of getting an email from the user to be a priority and as easy and as clean as possible.

**Comment by xmatthewx** [comment]
I like that it reduces the burden on this first step ... and that our splash page campaigns can maintain their dashing good looks.  

I'm okay with bumping it to the 2nd step "choose a username." We could compare opt-ins with it's current implementation to see if we're hurting or helping ourselves. 

cc @thisandagain @cassiemc @jbuck @vazquez @adamlofting

**Comment by cassiemc** [comment]
Sounds like a good plan to me so long as the testing is in place.

**Comment by ScottDowne** [comment]
Who do I talk to regarding testing? I'm not sure where to start with that.

Is the idea to compare current metrics with the new? or can we AB test it?

**Comment by xmatthewx** [comment]
@secretrobotron - Can you help wrangle a decision on if and how to do this?

**Comment by ScottDowne** [comment]
I was able to do this in #139.

Closing.
