### ISSUE TITLE
Improve x-ray goggles copy

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-login-ux#147]
Add some notion of changing the web you see to the blub about x-ray goggles that's displayed at the end of the current login flow. Just need to add "and change", like below:

> X-Ray Goggles allow you to see __and change__ the building blocks that make up websites on the Internet. Activate the goggles to inspect the code behind any webpage.

/cc @xmatthewx @ScottDowne @thisandagain

**Comment by xmatthewx** [comment]
We should also nix the word inspect. Maybe 'play with' instead? 

> X-Ray Goggles allow you to see and change the building blocks that make up websites on the Internet. Activate the goggles to **play with** the code behind any webpage.

**Comment by secretrobotron** [comment]
:+1:
