### ISSUE TITLE
Show only x-ray goggles modal if using onboarding login flow

### ISSUE THREAD

**Issue by secretrobotron** [mozilla/webmaker-login-ux#148]
For the new [on-boarding experience](https://github.com/MozillaFoundation/plan/issues/60), the user should just see the x-ray goggles modal after creating a username, and none of the others (i.e. instead of it being random).

**Comment by secretrobotron** [comment]
Related to #1072

**Comment by ScottDowne** [comment]
https://github.com/mozilla/webmaker-login-ux/pull/150

**Comment by secretrobotron** [comment]
x-ray goggles modal is shown for *any* flow.
